[package]
name = "rfc5545-types"
version = "0.1.0"
edition = "2024"
repository.workspace = true
license.workspace = true

[dependencies]
calendar-types = { version = "0.1.0", path = "../calendar-types" }
dizzy = "0.2.0"
