[workspace]
members = ["calendar-types", "calico", "jscalendar", "rfc5545-types"]
resolver = "2"

[workspace.package]
repository = "https://github.com/eikopf/calendar-crates"
license = "MIT"

[workspace.dependencies]
dizzy = "0.2.0"
strum = { version = "0.27.2", features = ["derive", "phf"] }
