[package]
name = "jscalendar"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde"]
serde_json = ["dep:serde_json"]

[dependencies]
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
