[package]
name = "calendar-types"
version = "0.1.0"
edition = "2024"
repository.workspace = true
license.workspace = true

[dependencies]
dizzy = "0.2.0"
strum = { version = "0.27.2", features = ["derive", "phf"] }
thiserror = "2.0.18"
